#!/usr/bin/env sh

TITLE=$1
PRIORITY=$2
INITTAG=$3

FILE="new/$(echo $TITLE | sed 's/ /-/g').md"

DIR=`pwd`

cd `cat .gitick`

echo "# $TITLE" >> $FILE
echo priority: $PRIORITY >> $FILE
echo tags: [$INITTAG] >> $FILE
echo date: `date` >> $FILE
echo reported: `git config user.name` >> $FILE
echo '' >> $FILE
echo "# LOG" >> $FILE

if [ -n "$4" ]; then
    echo "Don't Forget To Fill In Your Ticket!"
    echo ""
else
    nano $FILE
fi

cd $DIR


