#!/usr/bin/env sh

TITLE=$1
PRIORITY=$2
INITTAG=$3

FILE="new/$(echo $TITLE | sed 's/ /-/g').md"

DIR=`pwd`

cd `cat .gitick`

echo priority: $PRIORITY >> $FILE
echo tags: [$INITTAG] >> $FILE
echo date: `date` >> $FILE
echo reported: `git config user.name` >> $FILE
echo '' >> $FILE
echo "# $TITLE" >> $FILE
echo '' >> $FILE
echo "# LOG" >> $FILE

cd $DIR


