#!/usr/bin/env sh

PROJ=$1

mkdir $PROJ.gitick
cd $PROJ.gitick
echo '.' > .gitick
mkdir new
echo '..' > new/.gitick
mkdir new/need-info
echo '../..' > new/need-info/.gitick
git init .
git add .
git commit -m "initial commit for $PROJ"

